"use client";

import Link from "next/link";
import Image from "next/image";
import { ArrowUpRight, ArrowRight, Sun, Layers3, BookOpen, TrendingDown, Menu, X, MoveUpRight, Check, Github } from "lucide-react";
import { useState } from "react";

export function SiteHeader({section}:{section:string}) {
  const [open,setOpen]=useState(false);
  const links=[["Explore","/","home"],["Design studio","/planner","planner"],["Price tracker","/products","products"],["Learn solar","/guides","guides"],["Calculators","/calculators","calculators"]];
  return <header className="s4-header"><Link href="/" className="s4-logo" aria-label="Solar4U home"><Sun size={29} strokeWidth={1.8}/><span>solar4u<span className="s4-logo-dot">.</span></span></Link><button className="s4-menu" onClick={()=>setOpen(!open)} aria-label={open?"Close navigation":"Open navigation"} aria-expanded={open}>{open?<X/>:<Menu/>}</button><nav aria-label="Main navigation" className={open?"is-open":""}>{links.map(([name,href,key])=><Link key={key} href={href} onClick={()=>setOpen(false)} aria-current={section===key?"page":undefined}>{name}</Link>)}</nav><Link href="/dashboard" className="s4-header-project">My workspace <ArrowUpRight size={16}/></Link></header>;
}

export function SiteFooter(){return <footer className="s4-footer"><div><Link href="/" className="s4-logo"><Sun size={26}/><span>solar4u.</span></Link><p>A little knowledge.<br/>A lot more independence.</p></div><div><strong>Make a plan</strong><Link href="/planner">Roof & ground studio</Link><Link href="/calculators">Run the numbers</Link><Link href="/solar-part-picker">Build an equipment list</Link></div><div><strong>Do your research</strong><Link href="/guides">Solar field guide</Link><Link href="/products">Daily price tracker</Link><Link href="/diagnostics">Connection & tool status</Link><a href="https://github.com/FahadArfin/Solar4U" target="_blank" rel="noreferrer"><Github size={14}/> Open source</a></div><div className="s4-footer-note"><strong>Good plans start with good assumptions.</strong><p>Planning information only. Confirm electrical, structural, fire access and utility requirements with qualified local professionals. Your workspace saves on this device; export a backup to keep it.</p><small>© {new Date().getFullYear()} Solar4U · Built for the curious.</small></div></footer>}

export function NewHome(){return <main className="s4-main">
  <section className="s4-hero"><div className="s4-hero-copy"><div className="s4-kicker"><span/> THE FUTURE IS ON YOUR ROOF</div><h1>Your place.<br/>Your power.<br/><em>Your move.</em></h1><p>Make sense of solar. Explore your property, find the right equipment, and build a plan you actually understand.</p><div className="s4-actions"><Link className="s4-button s4-dark" href="/planner">Design my solar <ArrowUpRight size={19}/></Link><Link className="s4-text-link" href="/guides">Start with the basics <ArrowRight size={18}/></Link></div><div className="s4-hero-proof"><span><Check size={14}/> Start at your own pace</span><span><Check size={14}/> Your plan, saved on your device</span></div></div><div className="s4-hero-media"><Image src="/solar-home.png" fill priority unoptimized alt="Conceptual home with rooftop solar and a ground array, illustrating two ways to make your own energy" sizes="(max-width: 800px) 100vw, 55vw"/><div className="s4-image-label"><Sun size={18}/><span>Good energy starts at home<small>A concept to explore. A plan to make yours.</small></span></div><Link href="/planner" className="s4-image-open" aria-label="Open the solar design studio"><MoveUpRight/></Link></div></section>
  <section className="s4-path-strip" aria-label="Your solar journey"><span>FROM CURIOUS<br/><b>TO CONFIDENT.</b></span>{[["01","Understand your energy","/guides"],["02","See what fits","/planner"],["03","Find your equipment","/products"]].map(([n,t,h])=><Link href={h} key={n}><small>{n}</small><b>{t}</b><ArrowUpRight size={20}/></Link>)}</section>
  <section className="s4-section"><div className="s4-section-heading"><div><div className="s4-kicker">LESS GUESSWORK. MORE POSSIBILITY.</div><h2>Everything you need<br/>to make your next move.</h2></div><p>One connected workspace, from your first<br/>question to a considered solar plan.</p></div><div className="s4-feature-grid"><Link className="s4-feature s4-feature-green" href="/planner"><div className="s4-feature-top"><Layers3/><span>01 / DESIGN</span><ArrowUpRight/></div><h3>A new perspective<br/>on your property.</h3><p>Explore roof and ground layouts. Adjust your dimensions and see your solar plan take shape.</p><span className="s4-feature-bottom">Enter the design studio <ArrowRight size={18}/></span></Link><Link className="s4-feature" href="/products"><div className="s4-feature-top"><TrendingDown/><span>02 / COMPARE</span><ArrowUpRight/></div><h3>A clearer view<br/>of the price.</h3><p>Compare dated observations, see each source’s collection status, and follow the equipment that matters.</p><span className="s4-feature-bottom">Explore the price tracker <ArrowRight size={18}/></span></Link><Link className="s4-feature s4-feature-yellow" href="/guides"><div className="s4-feature-top"><BookOpen/><span>03 / LEARN</span><ArrowUpRight/></div><h3>Start small.<br/>Understand more.</h3><p>Learn one useful idea at a time, with worked examples, visual explanations and a clear next step.</p><span className="s4-feature-bottom">Open the solar field guide <ArrowRight size={18}/></span></Link></div></section>
  <section className="s4-manifesto"><div><div className="s4-kicker">INDEPENDENT BY DESIGN</div><h2>Better questions.<br/><em>Better energy decisions.</em></h2></div><div><p>You don’t need to know every acronym to get started. You need useful tools, visible assumptions, and a way to tell a measured result from an estimate.</p><Link href="/guides" className="s4-text-link">Let’s make solar make sense <ArrowRight size={18}/></Link></div></section>
  </main>}

export function WorkspacePage(){return <main className="s4-page"><div className="s4-kicker">YOUR OWN ENERGY WORKSPACE</div><h1>Pick up where<br/><em>you left off.</em></h1><p className="s4-lead">Your project and learning progress stay in this browser. Open the studio to resume your saved plan or export a portable backup.</p><div className="s4-feature-grid">{[["Design studio","Continue your roof or ground plan.","/planner"],["Learning path","Resume your lessons and knowledge checks.","/guides"],["Equipment watchlist","Return to the products you’re following.","/products"]].map(([t,p,h])=><Link className="s4-feature" key={h} href={h}><ArrowUpRight/><h3>{t}</h3><p>{p}</p><span className="s4-feature-bottom">Open workspace <ArrowRight size={18}/></span></Link>)}</div></main>}

