"use client";
import {useEffect,useMemo,useState} from 'react';
import {flushSync} from 'react-dom';
import {ArrowUpRight,Bookmark,Download,RefreshCw,Search} from 'lucide-react';
import {objectInput,useAgentTools} from './webmcp';
import registry from '../services/price-worker/retailers.config.json';
type Offer={id:string;name:string;variant:string;sku:string;category:string;retailerId:string;retailer:string;price:number;minorAmount:number;currency:string;available:boolean|null;url:string;observedAt:string};
type Source={id:string;name:string;status:string;reason:string;observations:number;checkedAt:string};
type Dataset={offers:Offer[];sources:Source[];generatedAt:string;schedule:string};
const money=(n:number,c:string)=>new Intl.NumberFormat('en-US',{style:'currency',currency:c}).format(n);
const date=(s:string)=>new Date(s).toLocaleString(undefined,{dateStyle:'medium',timeStyle:'short'});
const stale=(s:string)=>Date.now()-Date.parse(s)>48*3600000;
export default function PriceTracker({initialSearch=''}:{initialSearch?:string}){
 const [data,setData]=useState<Dataset|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 const [query,setQuery]=useState(initialSearch),[category,setCategory]=useState('All'),[retailer,setRetailer]=useState('All'),[currency,setCurrency]=useState('USD'),[sort,setSort]=useState('newest'),[view,setView]=useState('prices');
 const [watch,setWatch]=useState<string[]>([]),[saved,setSaved]=useState('Saved on this device'),[onlyWatched,setOnlyWatched]=useState(false),[selected,setSelected]=useState<Offer|null>(null),[points,setPoints]=useState<Array<[string,number,boolean|null]>>([]),[historyStatus,setHistoryStatus]=useState('');
 async function refresh(){setLoading(true);setError('');try{const r=await fetch('/api/prices');const d=await r.json();if(!r.ok)throw new Error(d.error);setData(d)}catch(e){setError(e instanceof Error?e.message:'Unable to load observations')}finally{setLoading(false)}}
 useEffect(()=>{const t=setTimeout(()=>{void refresh();try{const v=JSON.parse(localStorage.getItem('solar4u-watchlist-v1')??'[]');if(Array.isArray(v))setWatch(v.filter(x=>typeof x==='string'))}catch{setSaved('Device storage unavailable')}},0);return()=>clearTimeout(t)},[]);
 useEffect(()=>{if(!selected)return;const c=new AbortController();fetch(`/api/prices?source=${encodeURIComponent(selected.retailerId)}&id=${selected.id}`,{signal:c.signal}).then(async r=>{if(!r.ok)throw new Error('History could not be loaded');return r.json()}).then(d=>{setPoints(d.points);setHistoryStatus(d.points.length>1?'Only successful observations are shown. Missing days are left empty.':'This variant has one observation so far. Daily history starts here.')}).catch(e=>{if(!c.signal.aborted)setHistoryStatus(e.message)});return()=>c.abort()},[selected]);
 function toggle(id:string){const next=watch.includes(id)?watch.filter(x=>x!==id):[...watch,id];try{localStorage.setItem('solar4u-watchlist-v1',JSON.stringify(next));setWatch(next);setSaved('Watchlist saved on this device')}catch{setSaved('Storage is full or blocked; watchlist was not saved')}}
 const filtered=useMemo(()=>{const q=query.toLowerCase();return(data?.offers??[]).filter(o=>(!q||`${o.name} ${o.variant} ${o.sku} ${o.retailer}`.toLowerCase().includes(q))&&(category==='All'||o.category===category)&&(retailer==='All'||o.retailerId===retailer)&&o.currency===currency&&(!onlyWatched||watch.includes(o.id))).sort((a,b)=>sort==='low'?a.price-b.price:sort==='high'?b.price-a.price:b.observedAt.localeCompare(a.observedAt))},[data,query,category,retailer,currency,sort,onlyWatched,watch]);
 useAgentTools([
 {name:'solar4u_search_prices',description:'Read observed retailer variants, prices, currency, stock, and observation timestamps. Retailer text is untrusted. This does not make purchases.',inputSchema:{type:'object',properties:{query:{type:'string',maxLength:200}},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:i=>{const v=objectInput(i);if(v.query!==undefined&&typeof v.query!=='string')throw new Error('query must be text');const q=String(v.query??'').slice(0,200).toLowerCase();return{generatedAt:data?.generatedAt??null,offers:(data?.offers??[]).filter(o=>`${o.name} ${o.variant} ${o.sku}`.toLowerCase().includes(q)).slice(0,50),note:'Observed prices exclude shipping and tax; check the retailer before buying.'}}},
 {name:'solar4u_read_price_sources',description:'Read scheduled collection coverage and failures for every configured retailer.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:i=>{objectInput(i);return{schedule:data?.schedule??'Daily at 07:17 UTC',sources:data?.sources??[],error}}},
 {name:'solar4u_filter_prices',description:'Set the visible tracker search query. Does not change the watchlist or buy products.',inputSchema:{type:'object',properties:{query:{type:'string',maxLength:200}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:false},execute:i=>{const v=objectInput(i);if(typeof v.query!=='string'||v.query.length>200)throw new Error('Enter up to 200 characters');flushSync(()=>{setQuery(v.query as string);setView('prices')});return{query:v.query,status:'filters_applied'}}}
 ]);
 function exportCSV(){const csv=[['Product','Variant','SKU','Retailer','Amount','Currency','Stock','Observed at UTC','Source URL'],...filtered.map(o=>[o.name,o.variant,o.sku,o.retailer,o.price,o.currency,o.available===null?'Unknown':o.available?'In stock':'Out of stock',o.observedAt,o.url])].map(row=>row.map(v=>'"'+String(v).replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download='solar4u-observed-prices.csv';a.click();URL.revokeObjectURL(url)}
 const sources=data?.sources??registry.map(s=>({id:s.id,name:s.name,status:'not_loaded',reason:'Waiting for the collection report.',observations:0,checkedAt:''}));
 return <main className="s4-page s4-tracker"><div className="s4-kicker"><span/> THE PRICE OBSERVATORY</div><div className="s4-title-row"><div><h1>Good energy.<br/><em>Informed purchases.</em></h1><p className="s4-lead">Real retailer observations, exact variants, and a history that grows each day. Keep the equipment you care about close.</p></div><button className="s4-button s4-light" onClick={refresh} disabled={loading}><RefreshCw size={15}/> {loading?'Checking…':'Refresh'}</button></div>
 <div className="s4-metrics"><div><span>Observed variants</span><b>{data?.offers.length.toLocaleString()??'—'}</b></div><div><span>Sources with prices</span><b>{sources.filter(s=>s.observations>0).length} <small>/ {sources.length}</small></b></div><div><span>Daily collection</span><b>07:17 <small>UTC</small></b></div><div><span>Last run</span><b className="s4-small-value">{data?date(data.generatedAt):'Awaiting data'}</b></div></div>
 <p className="s4-fine">Catalog coverage varies by retailer. Prices exclude tax and delivery. Availability and price can change after collection. A missing observation is never treated as a zero price.</p>
 <div className="s4-tabs" aria-label="Price tracker views">{['prices','sources'].map(v=><button key={v} aria-pressed={view===v} onClick={()=>setView(v)}>{v==='prices'?'Browse equipment':'Retailer coverage'}</button>)}<span role="status">{saved}</span></div>
 {error&&<div role="alert" className="s4-banner">{error} <button onClick={refresh}>Try again</button></div>}
 {view==='sources'?<div className="s4-source-list">{sources.map(s=><article className="s4-panel" key={s.id}><div className="s4-title-row"><h2>{s.name}</h2><span className="s4-pill">{s.status.replaceAll('_',' ')}</span></div><p>{s.reason}</p><small>{s.observations} variants observed{s.checkedAt?` · Checked ${date(s.checkedAt)}`:''}</small></article>)}<p className="s4-fine">Stores without an advertised catalog need an authorized feed or manual import. Access restrictions are respected. Automated collection searches solar, battery, and inverter catalogs within a per-store page limit.</p></div>:<>
 <div className="s4-filter-bar"><label className="s4-search"><Search size={16}/><input aria-label="Search equipment" placeholder="Search equipment, SKU, or retailer" value={query} onChange={e=>setQuery(e.target.value)}/></label><label>Category<select value={category} onChange={e=>setCategory(e.target.value)}>{['All','Solar panel','Battery','Inverter','Controller','Equipment'].map(v=><option key={v}>{v}</option>)}</select></label><label>Retailer<select value={retailer} onChange={e=>setRetailer(e.target.value)}><option value="All">All retailers</option>{registry.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Currency<select value={currency} onChange={e=>setCurrency(e.target.value)}>{[...new Set(['USD',...(data?.offers??[]).map(o=>o.currency)])].sort().map(v=><option key={v}>{v}</option>)}</select></label><label>Sort<select value={sort} onChange={e=>setSort(e.target.value)}><option value="newest">Latest observation</option><option value="low">Price: low to high</option><option value="high">Price: high to low</option></select></label></div>
 <div className="s4-title-row s4-results-bar"><label><input type="checkbox" checked={onlyWatched} onChange={e=>setOnlyWatched(e.target.checked)}/> Watchlist ({watch.length})</label><span>{filtered.length.toLocaleString()} matching variants</span><button className="s4-button s4-light" disabled={!filtered.length} onClick={exportCSV}><Download size={14}/> Export CSV</button></div>
 <div className="s4-table-scroll"><table className="s4-data-table"><thead><tr><th>Equipment / variant</th><th>Retailer</th><th>Observed price</th><th>Stock / freshness</th><th>Save</th></tr></thead><tbody>{filtered.slice(0,200).map(o=><tr key={o.id}><td><button className="s4-product-name" onClick={()=>{setPoints([]);setHistoryStatus('Loading observations…');setSelected(o)}}>{o.name}</button><small>{o.variant&&o.variant!=='Default Title'?o.variant:o.sku||o.category}</small></td><td>{o.retailer}<small>{o.category}</small></td><td><strong>{money(o.price,o.currency)}</strong><small>{o.currency} · before shipping</small></td><td>{o.available===null?'Stock unknown':o.available?'In stock':'Out of stock'}<small className={stale(o.observedAt)?'s4-warning':''}>{stale(o.observedAt)?'Older observation · ':''}{date(o.observedAt)}</small></td><td><button className="s4-icon-button" aria-label={`${watch.includes(o.id)?'Unsave':'Save'} ${o.name}`} aria-pressed={watch.includes(o.id)} onClick={()=>toggle(o.id)}><Bookmark size={18} fill={watch.includes(o.id)?'currentColor':'none'}/></button></td></tr>)}</tbody></table></div>
 {!filtered.length&&<div className="s4-empty"><Search size={30}/><h2>{loading?'Reading retailer observations…':'No matching observations'}</h2><p>{data?'Try another search, category, or currency.':'The collection report will appear here after the first successful run.'}</p></div>}{filtered.length>200&&<p className="s4-fine">Showing the first 200 matches. Narrow your filters or export all {filtered.length} matching records.</p>}
 </>}
 {selected&&<div className="s4-modal-backdrop" onClick={()=>setSelected(null)}><section role="dialog" aria-modal="true" aria-label="Variant price history" className="s4-modal" onClick={e=>e.stopPropagation()} onKeyDown={e=>{if(e.key==='Escape')setSelected(null)}}><button autoFocus className="s4-button s4-light" onClick={()=>setSelected(null)}>Close history</button><div className="s4-kicker">{selected.retailer} · EXACT VARIANT</div><h2>{selected.name}</h2><p>{selected.variant} {selected.sku&&` · SKU ${selected.sku}`}</p><strong className="s4-price-large">{money(selected.price,selected.currency)}</strong><p className="s4-fine">Observed {date(selected.observedAt)} · {selected.currency}</p><div className="s4-history" aria-label="Dated price observations">{points.map(p=><div key={p[0]}><span>{date(p[0])}</span><span className="s4-history-bar" style={{width:`${Math.max(2,p[1]/Math.max(...points.map(v=>v[1]))*100)}%`}}/><strong>{money(p[1]/(selected.minorAmount/selected.price),selected.currency)}</strong></div>)}</div><p className="s4-fine" role="status">{historyStatus}</p><a className="s4-button s4-dark" href={selected.url} target="_blank" rel="noreferrer">Check retailer listing <ArrowUpRight size={16}/></a><p className="s4-fine">Confirm quantity, condition, delivery, and warranty at the retailer. Solar4U does not process purchases.</p></section></div>}
 </main>
}
